src/Interpolations/grid_to_particle.jl
src/Interpolations/particle_to_grid.jl

Several fields can be interpolated in a single function call/kernel :
```julia
T, P = rand(20,20), rand(20,20)
particle_args = init_cell_arrays(particles, Val(2))
grid2particle!(particle_args, xvi, (T, P), particles.coords)
particle2grid!((T, P), particle_args, xvi, particles.coords)
```

Fuse interpolations of several fields

---

src/Interpolations/grid_to_particle.jl
src/Interpolations/particle_to_grid.jl

Fixes broken code from #4

---

scripts/temperature_advection_AMDGPU.jl
src/JustPIC.jl
src/Particles/advection.jl

AMDGPU tested and working on Lumi.
For the future. `rand` and fold-like reduction methods do not work on AMDGPU kernels.

Fix AMDGPU

---

scripts/temperature_advection.jl
src/Particles/injection.jl
src/Particles/shuffle.jl
src/Particles/utils.jl

Complements and fixes #10 and #11

Injection on AMDGPU

---

scripts/rotating_circle.jl

Reproduces the benchmark in  Fig.5 of https://doi.org/10.5194/gmd-2023-189, 2023

Rotating circle benchmark

---

scripts/single_particle_advection.jl
scripts/single_particle_advection_MPI.jl
scripts/temperature_advection.jl
scripts/temperature_advection3d.jl
src/Interpolations/particle_to_grid.jl

And defaults examples to `Threads`

Fix minor indexing bug 

---

src/Particles/move.jl
src/particles.jl
test/test_2D.jl
test/test_3D.jl

Fixes the bug reported by @paellig and adds some extra unit testing.

Fix bug in `move_particles!`

---

scripts/temperature_advection3d.jl
src/Particles/particles_utils.jl
test/test_2D.jl
test/test_3D.jl

Implements suggestions by @paellig

Homogenizes the particles initialization for 2 and 3 dimensions

---

README.md
test/runtests.jl

This PR fixes an issue when running tests as separate Julia processes would not trigger code coverage.

Fix Codecov

---

.github/workflows/UnitTests.yml

trying to fix the failed upload to codecov

test codecov upload

---

src/Interpolations/centroid_to_particle.jl
src/Particles/utils.jl

Fix AMDGPU support

---

Project.toml
docs/make.jl
docs/src/field_advection2D.md
docs/src/field_advection3D.md
ext/JustPICAMDGPUExt.jl
ext/JustPICCUDAExt.jl
scripts/rotating_circle.jl
scripts/rotating_marker_chain.jl
scripts/rotating_passive_markers.jl
scripts/single_particle_advection.jl
scripts/single_particle_advection_MPI.jl
scripts/temperature_advection.jl
scripts/temperature_advection3d.jl
scripts/temperature_advection_AMDGPU.jl
scripts/temperature_advection_MPI.jl
src/JustPIC.jl
src/JustPIC_CPU.jl
test/test_2D.jl
test/test_3D.jl

Unexports the backend types to avoid conflicts with other pkgs.

Unexport backends

---

ext/JustPICAMDGPUExt.jl
ext/JustPICCUDAExt.jl
src/PhaseRatios/kernels.jl
src/common.jl
test/test_CellArrays.jl

`update_phase_ratios!` computes the phase ratios on the cell centers and vertices

Fuse center and vertex phase ratio functions

---

scripts/SolCx/pureshear_ALE_restart.jl
scripts/pureshear_ALE_restart.jl

* add pure shear ALE example with demo for a restart option
* corrected previous pure shear example

add restart example

---

.buildkite/pipeline.yml
ext/JustPICAMDGPUExt.jl
ext/JustPICCUDAExt.jl
src/CellArrays/conversion.jl
test/test_save_load.jl

Avoids `AbstractArray` fallback.

Custom GPU conversion for CellArrays

---

src/Particles/particles_utils.jl

This bug was introduced in #160

Fix bug in initial marker distribution

---

scripts/pureshear_ALE.jl
scripts/temperature_advection.jl
scripts/temperature_advection3d.jl
src/Particles/injection.jl
src/Particles/move_safe.jl
test/test_2D.jl
test/test_3D.jl

Refines the injection algorithm by diving a cell into 4 (2D) or 8 (3D) sub cells.

Injection by cell quadrants

---

ext/JustPICAMDGPUExt.jl
ext/JustPICCUDAExt.jl
src/JustPIC_CPU.jl
test/test_2D.jl

Removes the initialization of ParallelStencil inside `__init__`

Remote __init__()

---

ext/JustPICAMDGPUExt.jl
ext/JustPICCUDAExt.jl
scripts/temperature_advection3D_MPI.jl
scripts/temperature_advection3d.jl
scripts/temperature_advection_MPI.jl

Adds missing methods in the extensions to fix the halo updates of GPU CellArrays.

Fix GPU halo updates

---

.github/workflows/Format.yml
ext/JustPICAMDGPUExt.jl
ext/JustPICCUDAExt.jl
scripts/pureshear_ALE.jl
scripts/pureshear_ALE_restart.jl
scripts/rotating_circle.jl
scripts/rotating_marker_chain.jl
scripts/rotating_passive_markers.jl
scripts/single_particle_advection.jl
scripts/single_particle_advection_MPI.jl
scripts/temperature_advection.jl
scripts/temperature_advection3d.jl
scripts/temperature_advection_AMDGPU.jl
scripts/temperature_advection_LinP.jl
scripts/temperature_advection_MPI.jl
scripts/temperature_advection_centroid.jl
scripts/temperature_advection_counter_rotation.jl
scripts/temperature_advection_timer.jl
src/Particles/Advection/advection.jl
src/Particles/injection.jl
src/Particles/particles_utils.jl
src/Particles/utils.jl
src/Utils.jl
test/test_2D.jl
test/test_3D.jl

Where 0 < `buffer` < 1  is the `(1-buffer) * dx` distance left between the injected particle and the cell boundaries.

Add buffer kwarg to `init_particles`

---

.buildkite/pipeline.yml
.buildkite/run_tests.yml

This PR enables the conditional trigger of GPU Buildkite CI only when GPU-relevant files are modified.

Conditional GPU CI trigger

---

ext/JustPICAMDGPUExt.jl
ext/JustPICCUDAExt.jl
src/MarkerChain/Advection/advection.jl
src/MarkerChain/Advection/interp_velocity.jl
src/common.jl

Example of usage:
```julia
n        = 51
nx       = n-1
Lx       = Ly = 1.0
xvi      = xv, yv = LinRange(0, Lx, n), LinRange(0, Ly, n)
dxi      = dx, dy = xv[2] - xv[1], yv[2] - yv[1]
xc, yc   = LinRange(0+dx/2, Lx-dx/2, n-1), LinRange(0+dy/2, Ly-dy/2, n-1)
grid_vx  = xv, expand_range(yc)
grid_vy  = expand_range(xc), yv
grid_vxi = grid_vx, grid_vy
Vx       = TA(backend)([-vi_stream(y) for x in grid_vx[1], y in grid_vx[2]]);
Vy       = TA(backend)([ vi_stream(x) for x in grid_vy[1], y in grid_vy[2]]);
nxcell, min_xcell, max_xcell = 12, 6, 24
initial_elevation = Ly/2
chain             = init_markerchain(backend, nxcell, min_xcell, max_xcell, xv, initial_elevation);
chain_V  = similar(chain.coords[1]), similar(chain.coords[1]);
chain_V[1].data  .*= 0
chain_V[2].data  .*= 0 …
```

Interpolate velocty to marcher chain

---

src/MarkerChain/areas.jl

Remove `@show` that slipped through during the last PR

Remove debugging `@show`
